version: '3.9'

services:
  db:
    image: postgres:15
    container_name: inventoryhub_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventoryhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventoryhub_network

  api:
    build: .
    container_name: inventoryhub_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - inventoryhub_network

volumes:
  postgres_data:

networks:
  inventoryhub_network:
    driver: bridge